/**
 * Minimal, dependency-free PDF generator. Builds a valid single-page PDF
 * (Helvetica + Helvetica-Bold) with a branded header — a monogram "logo" mark in
 * the tenant accent colour, the company name and product name — followed by a
 * title, subtitle and label/value rows. ASCII-only content keeps byte offsets
 * exact, so no PDF library is needed.
 */
export interface PdfBrand {
  company: string;
  monogram: string;
  primary?: string; // hex — company name colour
  accent?: string; // hex — logo mark colour
  product?: string; // e.g. "Diigoo ERP · Unified Retail Commerce"
}

/** "#1B2A4A" → "0.106 0.165 0.290" (PDF rg/RG operands). */
function rgb(hex: string): string {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  const n = parseInt(full, 16);
  const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
  return `${(r / 255).toFixed(3)} ${(g / 255).toFixed(3)} ${(b / 255).toFixed(3)}`;
}

export function downloadPdf(filename: string, title: string, rows: [string, string][], subtitle?: string, brand?: PdfBrand) {
  const ascii = (s: string) => String(s).replace(/[^\x20-\x7E]/g, "-");
  const esc = (s: string) => ascii(s).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  const company = brand?.company ?? "Northwind Retail Group";
  const monogram = (brand?.monogram ?? company.slice(0, 2)).toUpperCase();
  const navy = brand?.primary ?? "#1B2A4A";
  const accent = brand?.accent ?? "#004680";
  const product = brand?.product ?? "Diigoo ERP - Unified Retail Commerce";
  const gray = "#64748B";
  const line = "#D7DCE3";

  const C: string[] = [];
  // ── Branded header ──
  // Logo mark: accent square with the company monogram.
  C.push(`${rgb(accent)} rg`, "72 734 30 30 re f");
  C.push("1 1 1 rg", "BT", "/F2 13 Tf", "79 743 Td", `(${esc(monogram)}) Tj`, "ET");
  // Company name + product line.
  C.push(`${rgb(navy)} rg`, "BT", "/F2 15 Tf", "112 750 Td", `(${esc(company)}) Tj`, "ET");
  C.push(`${rgb(gray)} rg`, "BT", "/F1 9 Tf", "112 737 Td", `(${esc(product)}) Tj`, "ET");
  // Divider.
  C.push(`${rgb(line)} RG`, "0.8 w", "72 724 m 540 724 l S");

  // ── Document title + subtitle ──
  C.push(`${rgb(navy)} rg`, "BT", "/F2 18 Tf", "72 696 Td", `(${esc(title)}) Tj`, "ET");
  if (subtitle) C.push(`${rgb(gray)} rg`, "BT", "/F1 10 Tf", "72 678 Td", `(${esc(subtitle)}) Tj`, "ET");

  // ── Rows ──
  C.push("0.12 0.16 0.22 rg", "BT", "/F1 12 Tf", "72 648 Td");
  for (const [label, value] of rows) {
    C.push(`(${esc(label + ":")}) Tj`, "180 0 Td", `(${esc(value)}) Tj`, "-180 -22 Td");
  }
  C.push("ET");

  // ── Footer ──
  C.push(`${rgb(gray)} rg`, "BT", "/F1 8 Tf", "72 56 Td", `(${esc(`${company} - Generated by ${product}`)}) Tj`, "ET");

  const stream = C.join("\n");

  const objs = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objs.forEach((o, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((off) => {
    pdf += `${String(off).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;

  const blob = new Blob([pdf], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.toLowerCase().endsWith(".pdf") ? filename : filename.replace(/\.[^.]+$/, "") + ".pdf";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
